### ISSUE TITLE
docker badge showing invalid

### ISSUE THREAD

**Issue by PaulSayantan** [PaulSayantan/TermTube#10]
## issue
![Docker Build](https://img.shields.io/docker/cloud/build/belikesayantan/termtube?logo=docker&style=for-the-badge)

**Comment by ashish-patwal** [comment]
hey @PaulSayantan , i will love to  work on this issue

**Comment by PaulSayantan** [comment]
@ashish-patwal sure, go ahead

**Comment by ashish-patwal** [comment]
> @ashish-patwal sure, go ahead

Thanks !!
